### ISSUE TITLE
ImportError: No module named IPython.display

### ISSUE THREAD

**Issue by tobigithub** [tobigithub/tensorflow-deep-learning#2]
When running mandelbrot-tensorflow.py 

```
vm@ubuntu:~/tensorflow/tk$ python mandelbrot-tensorflow.py 
Traceback (most recent call last):
  File "mandelbrot-tensorflow.py", line 8, in <module>
    from IPython.display import clear_output, Image, display
ImportError: No module named IPython.display
```

**Comment by tobigithub** [comment]
Solution: 

```
sudo pip install ipython
```

which leads to error

```
vm@ubuntu:~/tensorflow/tk$ python mandelbrot-tensorflow.py 
Traceback (most recent call last):
  File "mandelbrot-tensorflow.py", line 9, in <module>
    import scipy.ndimage as nd
ImportError: No module named scipy.ndimage
```

**Comment by tobigithub** [comment]
Solution

```
sudo pip install scipy
```

which leads to 

```
Command "/usr/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-p9pAFf/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1yH0kh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-p9pAFf/scipy
```

This is the common Ubuntu CF. No sane normal person can interpret this error.

**Comment by tobigithub** [comment]
Because Ubuntu 13 is EOL (endo of life) the obvious solution

```
sudo apt-get install python-scipy
```

leads to 

```
Err http://us.archive.ubuntu.com/ubuntu/ saucy/universe python-scipy amd64 0.12.0-2ubuntu1
  404  Not Found [IP: 91.189.91.13 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/s/suitesparse/libamd2.2.0_3.4.0-3ubuntu1_amd64.deb  404  Not Found [IP: 91.189.91.13 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/s/suitesparse/libumfpack5.4.0_3.4.0-3ubuntu1_amd64.deb  404  Not Found [IP: 91.189.91.13 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/p/python-decorator/python-decorator_3.4.0-2_all.deb  404  Not Found [IP: 91.189.91.13 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/p/python-scipy/python-scipy_0.12.0-2ubuntu1_amd64.deb  404  Not Found [IP: 91.189.91.13 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Why let a perfectly fine system die?

Because its Soylent Green Time, every Ubuntu has to die after 9 month, unless its the upper class 
[LTS version](http://www.ubuntu.com/info/release-end-of-life). Well its like Windows XP, first it sucks, then it works and then it sucks big.

**Comment by tobigithub** [comment]
Another option would be to use Anaconda (python package library)
https://www.continuum.io/downloads
or this
https://conda.anaconda.org/jjhelmus
